version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
  app:
    build:
      context: . # Dockerfileのあるディレクトリ
      dockerfile: Dockerfile.dev # 開発環境用
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpack:
    build: 
      context: ./frontend # Dockerfileのあるディレクトリ
      dockerfile: Dockerfile.dev # 開発環境用
    command: npm run serve
    working_dir: "/app/frontend"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3500:3500"
    depends_on:
      - app

volumes:
  postgres-data: