version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
  app:
    build:
      context: . # Dockerfileのあるディレクトリ
      dockerfile: Dockerfile.dev # 開発環境用
    command: bundle exec puma -C config/puma.rb 
    volumes:
      - .:/app
      - /var/tmp
      # socketファイルの共有
      - sockets:/app/tmp/sockets/
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpack:
    build: 
      context: ./frontend # Dockerfileのあるディレクトリ
      dockerfile: Dockerfile.dev # 開発環境用
    command: npm run serve
    working_dir: "/app/frontend"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3500:3500"
    depends_on:
      - app
  nginx:
    build:
      context: ./nginx
    ports:
      - '80:80'
      #socketファイルの共有
    environment:
      SERVER_NAME: 'localhost'
    volumes: 
      - sockets:/app/tmp/sockets/
    depends_on: 
      - app
volumes:
  postgres-data:
  sockets: